name: Sincronizar Dados do SharePoint

on:
  schedule:
    - cron: '*/15 * * * *' # Executa a cada 15 minutos
  workflow_dispatch: # Permite rodar manualmente clicando em um botão

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Baixar dados.json do SharePoint/OneDrive
        run: |
          curl -L "https://senacam-my.sharepoint.com/:u:/g/personal/glauco_soprano_am_senac_br/IQAVBwaciPCrS7Kd5a6_38vSAbpawgtsUrHbD3XBKsMkxWo?e=5NEAQf&download=1" -o dados.json

      - name: Commit e Push para o Repositório
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dados.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Atualização automática de dados.json via SharePoint" && git push)
